Mage Duel!

Let's use what we've learned to play a mage duel!

Imagine your wizard has 6d4 health points and you have spells that do 6d4 damage. "6d4" means rolling six 4-sided dice and summing the result.

Your opposing mage has 4d6 health points and spells that do 4d6. "4d6" means rolling four six-sided dice and summing the result.

Exercises

Simulate mage duels to answer who is the more powerful mage?

Before running simulations, do you have a hypothesis of which mage will win? Do you have a hunch? Write it down. This is your first exercise.
Simulate 10 mage duels. Is there a clear winner? Run that 10 duel simulation again. Was the answer similar?
Do the results change much at 100 duels?
Now, simulate 10,000 mage duels. Is there a clear winner?

In [4]:
import numpy as np
import pandas as pd

In [5]:
wizard1 = np.random.choice([1,2,3,4], size = (10, 6))

In [11]:
wizard1sum = wizard1.sum(axis =1)

In [12]:
wizard1sum

array([17, 18, 18, 17, 13, 13, 19, 17, 17, 11])

In [13]:
wizard2 = np.random.choice([1,2,3,4,5,6], size = (10, 4))

In [14]:
wizard2

array([[4, 3, 4, 1],
       [1, 3, 4, 4],
       [2, 6, 5, 3],
       [2, 1, 1, 2],
       [3, 6, 4, 3],
       [5, 3, 5, 2],
       [2, 2, 5, 2],
       [2, 2, 6, 3],
       [3, 1, 1, 6],
       [2, 6, 2, 5]])

In [15]:
wizard2sum = wizard2.sum(axis = 1)

In [16]:
wizard2sum

array([12, 12, 16,  6, 16, 15, 11, 13, 11, 15])

#### height = pd.DataFrame({'Average Mens Height': men_height, 'Average Womens Height': women_height})

In [18]:
rolls = pd.DataFrame({'Wizard_1': wizard1sum, 'Wizard_2': wizard2sum})

In [19]:
rolls

Wizard_1  Wizard_2
0        17        12
1        18        12
2        18        16
3        17         6
4        13        16
5        13        15
6        19        11
7        17        13
8        17        11
9        11        15

In [ ]:
rolls['']