In [1]:
%matplotlib inline
import numpy as np
import pandas as pd
flips = np.random.choice(['Heads', 'Tails'], size =5)


In [2]:
flips == 'Heads'

array([False, False, False,  True, False])

In [3]:
(flips == 'Heads').mean()

0.2

In [4]:
#### as we increase the numer of trials, our acutal probability approaches the theoretical probability

In [5]:
flips = np.random.choice(['Heads', 'Tails'], size =100000)

In [6]:
(flips == 'Heads').mean()

0.50069

#### 1. How likely is it that you roll doubles when rolling two dice?

1. Represent your data
2. Make a matrix
3. Aggregate row-wise

In [9]:
roll_results = np.random.choice([1,2,3,4,5,6], size=(10_000 ,2))
roll_results

array([[4, 1],
       [1, 5],
       [4, 1],
       ...,
       [4, 4],
       [4, 6],
       [1, 1]])

- Because the row-wise aggregate is more complicated than an simple sum, turn the np array into a pandas dataframe

In [11]:
df = pd.DataFrame(roll_results)
df

0  1
0     4  1
1     1  5
2     4  1
3     3  3
4     1  1
...  .. ..
9995  5  3
9996  6  5
9997  4  4
9998  4  6
9999  1  1

[10000 rows x 2 columns]

- Now write a function that checks to see if each observation is a double (same number on each roll)
- Then apply that to the whole dataframe one row at a time

In [18]:
def are_doubles(one_observation: pd.Series) -> bool:
    return (one_observation == 1).all() or (one_observation == 2).all() or (one_observation == 3).all() or (one_observation == 4).all() or (one_observation == 5).all() or (one_observation == 6).all()

In [15]:
df.apply(are_doubles , axis = 1)

0       False
1       False
2       False
3        True
4        True
        ...  
9995    False
9996    False
9997     True
9998    False
9999     True
Length: 10000, dtype: bool

- To answer the question "How likely?" use the .mean() function to get a percent. This represents the probablitily that any of these rolls are doubles of any kind

In [19]:
df.apply(are_doubles , axis = 1).mean()

0.1683

#### 2. If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

- Represent your data
- Make a matrix
- Aggregate row-wise

- Step 1: Use an np array and random choice to represent the results of flipping 8 coins 10,000 times

In [22]:
flip_results = np.random.choice(["Heads","Tails"], size = (10_000, 8))
flip_results

array([['Heads', 'Heads', 'Tails', ..., 'Tails', 'Heads', 'Heads'],
       ['Tails', 'Heads', 'Tails', ..., 'Heads', 'Heads', 'Tails'],
       ['Tails', 'Tails', 'Heads', ..., 'Heads', 'Heads', 'Heads'],
       ...,
       ['Heads', 'Tails', 'Tails', ..., 'Tails', 'Heads', 'Tails'],
       ['Tails', 'Heads', 'Tails', ..., 'Heads', 'Heads', 'Tails'],
       ['Heads', 'Tails', 'Tails', ..., 'Tails', 'Tails', 'Tails']],
      dtype='<U5')

- Step 2: Turn results into boolean values where 'Heads' is True and 'Tails' is False

In [24]:
is_heads = (flip_results == 'Heads')
is_heads

array([[ True,  True, False, ..., False,  True,  True],
       [False,  True, False, ...,  True,  True, False],
       [False, False,  True, ...,  True,  True,  True],
       ...,
       [ True, False, False, ..., False,  True, False],
       [False,  True, False, ...,  True,  True, False],
       [ True, False, False, ..., False, False, False]])

- Step 3: Sum all the rows

In [27]:
number_of_heads_in_each_observation = is_heads.sum(axis=1)
number_of_heads_in_each_observation

array([5, 4, 5, ..., 2, 4, 1])

- Step 4: Count all the instances that the total equals 3. This represents only 3 heads in each observation or row

In [30]:
only_3_heads = (number_of_heads_in_each_observation == 3)
only_3_heads

array([False, False, False, ..., False, False, False])

- Step 4: To answer the question "What is the probablitily?" use the .mean() function.

In [31]:
only_3_heads.mean()

0.2252