In [1]:
%matplotlib inline
import numpy as np
import pandas as pd
flips = np.random.choice(['Heads', 'Tails'], size =5)


In [2]:
flips == 'Heads'

array([False, False, False, False, False])

In [3]:
(flips == 'Heads').mean()

0.0

In [4]:
#### as we increase the numer of trials, our acutal probability approaches the theoretical probability

In [5]:
flips = np.random.choice(['Heads', 'Tails'], size =100000)

In [6]:
(flips == 'Heads').mean()

0.49897

### 1. How likely is it that you roll doubles when rolling two dice?

1. Represent your data
2. Make a matrix
3. Aggregate row-wise

In [7]:
roll_results = np.random.choice([1,2,3,4,5,6], size=(10_000 ,2))
roll_results

array([[5, 6],
       [2, 2],
       [6, 4],
       ...,
       [4, 4],
       [5, 3],
       [2, 3]])

- Because the row-wise aggregate is more complicated than an simple sum, turn the np array into a pandas dataframe

In [8]:
df = pd.DataFrame(roll_results)
df

0  1
0     5  6
1     2  2
2     6  4
3     6  3
4     5  4
...  .. ..
9995  2  2
9996  1  4
9997  4  4
9998  5  3
9999  2  3

[10000 rows x 2 columns]

- Now write a function that checks to see if each observation is a double (same number on each roll)
- Then apply that to the whole dataframe one row at a time

In [9]:
def are_doubles(one_observation: pd.Series) -> bool:
    return (one_observation == 1).all() or (one_observation == 2).all() or (one_observation == 3).all() or (one_observation == 4).all() or (one_observation == 5).all() or (one_observation == 6).all()

In [10]:
df.apply(are_doubles , axis = 1)

0       False
1        True
2       False
3       False
4       False
        ...  
9995     True
9996    False
9997     True
9998    False
9999    False
Length: 10000, dtype: bool

- To answer the question "How likely?" use the .mean() function to get a percent. This represents the probablitily that any of these rolls are doubles of any kind

In [11]:
df.apply(are_doubles , axis = 1).mean()

0.1679

### 2. If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

- Represent your data
- Make a matrix
- Aggregate row-wise
- Aggregate of aggregate

- Step 1: Use an np array and random choice to represent the results of flipping 8 coins 10,000 times

In [12]:
flip_results = np.random.choice(["Heads","Tails"], size = (10_000, 8))
flip_results

array([['Tails', 'Heads', 'Tails', ..., 'Tails', 'Heads', 'Tails'],
       ['Tails', 'Tails', 'Tails', ..., 'Heads', 'Tails', 'Tails'],
       ['Tails', 'Tails', 'Heads', ..., 'Heads', 'Heads', 'Tails'],
       ...,
       ['Heads', 'Heads', 'Heads', ..., 'Heads', 'Heads', 'Tails'],
       ['Tails', 'Heads', 'Tails', ..., 'Heads', 'Heads', 'Heads'],
       ['Heads', 'Tails', 'Heads', ..., 'Tails', 'Tails', 'Heads']],
      dtype='<U5')

- Step 2: Turn results into boolean values where 'Heads' is True and 'Tails' is False

In [13]:
is_heads = (flip_results == 'Heads')
is_heads

array([[False,  True, False, ..., False,  True, False],
       [False, False, False, ...,  True, False, False],
       [False, False,  True, ...,  True,  True, False],
       ...,
       [ True,  True,  True, ...,  True,  True, False],
       [False,  True, False, ...,  True,  True,  True],
       [ True, False,  True, ..., False, False,  True]])

- Step 3: Sum all the rows

In [14]:
number_of_heads_in_each_observation = is_heads.sum(axis=1)
number_of_heads_in_each_observation

array([3, 2, 3, ..., 6, 5, 4])

- Step 4: Count all the instances that the total equals 3. This represents only 3 heads in each observation or row

In [15]:
only_3_heads = (number_of_heads_in_each_observation == 3)
only_3_heads

array([ True, False,  True, ..., False, False, False])

- Step 4: To answer the question "What is the probablitily?" use the .mean() function.

In [16]:
only_3_heads.mean()

0.2186

### 3. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

- Represent your data
- Make a matrix
- Aggregate row-wise
- Aggregate of aggregate

- Step 1: Represent the data in an np array. The number of trials is two as this represents the two bilboards the person will drive past. There is a higher probability that the student chosen will be from the web development class, so include a probability aregument that represents this

- There are 4 elements. Three of which are the same, one is different

In [17]:
cohorts = np.random.choice(["WD","DS"], size = (10_000, 2), p=[.75,.25])
cohorts

array([['WD', 'WD'],
       ['WD', 'WD'],
       ['DS', 'WD'],
       ...,
       ['WD', 'WD'],
       ['WD', 'WD'],
       ['WD', 'DS']], dtype='<U2')

- Step 2: Because the row-wise aggregate is more complicated than an simple sum, turn the np array into a pandas dataframe

In [18]:
cohortsdf = pd.DataFrame(cohorts)
cohortsdf

0   1
0     WD  WD
1     WD  WD
2     DS  WD
3     WD  WD
4     WD  DS
...   ..  ..
9995  WD  DS
9996  WD  WD
9997  WD  WD
9998  WD  WD
9999  WD  DS

[10000 rows x 2 columns]

- Step 3: Determine how many times both bilboards have a data science student by writing a function, then apply that function to the entire dataframe

In [19]:
def are_both_data_science(one_row: pd.Series) -> bool:
    return (one_row == 'DS').all()

In [20]:
cohortsdf.apply(are_both_data_science, axis = 1)

0       False
1       False
2       False
3       False
4       False
        ...  
9995    False
9996    False
9997    False
9998    False
9999    False
Length: 10000, dtype: bool

- Step 4: Now you have a dataframe that is showing whether or not each observation or row has both data science students. To answer the question "What are the odds?" use .mean()

In [21]:
what_are_the_odds = cohortsdf.apply(are_both_data_science, axis = 1).mean()

In [22]:
what_are_the_odds

0.0593

### 4. Codeup students buy, on average, 3 poptart packages (+- 1.5) a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon?

- Represent your data
- Make a matrix
- Aggregate row-wise
- Aggregate of aggregate

- Step 1: Represent the data that shows average of 3 poptart purchases with standard deviation of 1.5. Use np.random.normal

In [28]:
poptart_purchases = np.random.normal(3,1.5, size = (10_000, 5))
rounded_poptart_purchases = poptart_purchases.round()
rounded_poptart_purchases

array([[6., 3., 3., 5., 1.],
       [3., 3., 3., 6., 6.],
       [5., 2., 2., 3., 4.],
       ...,
       [1., 2., 2., 3., 3.],
       [2., 4., 3., 0., 3.],
       [5., 4., 1., 4., 1.]])

- Step 2: There must be at least 1 poptart left at the end of the day on Friday in order to make a purchase. Sum the days of the week and compare it to 16

In [24]:
rounded_poptart_purchases_sum = rounded_poptart_purchases.sum(axis=1)
rounded_poptart_purchases_sum

array([10.,  8., 20., ..., 14.,  9., 17.])

In [30]:
at_least_one_poptart_left_on_Friday = (rounded_poptart_purchases_sum <= 16)
at_least_one_poptart_left_on_Friday

array([ True,  True, False, ...,  True,  True, False])

- Step: 3 To answer the question "How likely?" use .mean()

In [32]:
at_least_one_poptart_left.mean()

0.6821

### 5. Compare Heights
### Men have an average height of 178 cm and standard deviation of 8cm.
### Women have a mean of 170, sd = 6cm.
### If a man and woman are chosen at random, P(woman taller than man)?

- Represent your data
- Make a matrix
- Aggregate row-wise
- Aggregate of aggregate

- Step 1: Represent data in np array with np.random.normal

In [34]:
men_height = np.random.normal(178, 8, size = 10_000)
men_height

array([175.05423902, 168.52316146, 165.90952254, ..., 183.94147867,
       176.78193995, 170.43059448])

In [37]:
women_height = np.random.normal(170, 6, size = 10_000)
women_height

array([168.63460469, 172.65180747, 165.73479903, ..., 165.87423234,
       166.250262  , 178.29445202])

- Step 2: Create dataframe with men and women heights

In [42]:
height = pd.DataFrame({'Average Mens Height': men_height, 'Average Womens Height': women_height})

In [43]:
height

Average Mens Height  Average Womens Height
0              175.054239             168.634605
1              168.523161             172.651807
2              165.909523             165.734799
3              174.957031             173.297431
4              171.466092             178.326102
...                   ...                    ...
9995           179.629859             173.860995
9996           190.199396             172.704282
9997           183.941479             165.874232
9998           176.781940             166.250262
9999           170.430594             178.294452

[10000 rows x 2 columns]

- Step 3: Compare if average height of women is more than average height of man. This will create a boolean value of the instances where this is True or False

In [49]:
height['Woman is taller than Man'] = (height['Average Womens Height'] > height['Average Mens Height'])

In [50]:
height

Average Mens Height  Average Womens Height  Woman is taller than Man
0              175.054239             168.634605                     False
1              168.523161             172.651807                      True
2              165.909523             165.734799                     False
3              174.957031             173.297431                     False
4              171.466092             178.326102                      True
...                   ...                    ...                       ...
9995           179.629859             173.860995                     False
9996           190.199396             172.704282                     False
9997           183.941479             165.874232                     False
9998           176.781940             166.250262                     False
9999           170.430594             178.294452                      True

[10000 rows x 3 columns]

In [54]:
probability_woman_is_taller_than_man= height['Woman is taller than Man'].mean()
odds

0.2069

### 6.  When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?
### What is the probability that we observe an installation issue within the first 150 students that download anaconda?

- Represent your data
- Make a matrix
- Aggregate row-wise
- Aggregate of aggregate

- Step 1: Represent data in np array with np.random.choice

In [60]:
install = np.random.choice(['corrupted','not corrupted'], size = (10_000 , 50), p=[.004, .996])
install

array([['not corrupted', 'not corrupted', 'not corrupted', ...,
        'not corrupted', 'not corrupted', 'not corrupted'],
       ['not corrupted', 'not corrupted', 'not corrupted', ...,
        'not corrupted', 'not corrupted', 'not corrupted'],
       ['not corrupted', 'not corrupted', 'not corrupted', ...,
        'not corrupted', 'not corrupted', 'not corrupted'],
       ...,
       ['not corrupted', 'not corrupted', 'not corrupted', ...,
        'not corrupted', 'not corrupted', 'not corrupted'],
       ['not corrupted', 'not corrupted', 'not corrupted', ...,
        'not corrupted', 'not corrupted', 'not corrupted'],
       ['not corrupted', 'not corrupted', 'not corrupted', ...,
        'not corrupted', 'not corrupted', 'not corrupted']], dtype='<U13')

- Step 2: Because the row-wise aggregate is more complicated than an simple sum, turn the np array into a pandas dataframe

In [65]:
installdf = pd.DataFrame(install)
installdf

0              1              2              3   \
0     not corrupted  not corrupted  not corrupted  not corrupted   
1     not corrupted  not corrupted  not corrupted  not corrupted   
2     not corrupted  not corrupted  not corrupted  not corrupted   
3     not corrupted  not corrupted  not corrupted  not corrupted   
4     not corrupted  not corrupted  not corrupted  not corrupted   
...             ...            ...            ...            ...   
9995  not corrupted  not corrupted  not corrupted  not corrupted   
9996  not corrupted  not corrupted  not corrupted  not corrupted   
9997  not corrupted  not corrupted  not corrupted  not corrupted   
9998  not corrupted  not corrupted  not corrupted  not corrupted   
9999  not corrupted  not corrupted  not corrupted  not corrupted   

                 4              5              6              7   \
0     not corrupted  not corrupted  not corrupted  not corrupted   
1     not corrupted  not corrupted  not corrupted  not corrupted   
2     not corrupted  not corrupted  not corrupted  not corrupted   
3     not corrupted  not corrupted  not corrupted  not corrupted   
4     not corrupted  not corrupted  not corrupted  not corrupted   
...             ...            ...            ...            ...   
9995  not corrupted  not corrupted  not corrupted  not corrupted   
9996  not corrupted  not corrupted  not corrupted  not corrupted   
9997  not corrupted  not corrupted  not corrupted  not corrupted   
9998  not corrupted  not corrupted  not corrupted  not corrupted   
9999  not corrupted  not corrupted  not corrupted  not corrupted   

                 8              9   ...             40             41  \
0     not corrupted  not corrupted  ...  not corrupted  not corrupted   
1     not corrupted  not corrupted  ...  not corrupted  not corrupted   
2     not corrupted  not corrupted  ...  not corrupted  not corrupted   
3     not corrupted  not corrupted  ...  not corrupted  not corrupted   
4     not corrupted  not corrupted  ...  not corrupted  not corrupted   
...             ...            ...  ...            ...            ...   
9995  not corrupted  not corrupted  ...  not corrupted  not corrupted   
9996  not corrupted  not corrupted  ...  not corrupted  not corrupted   
9997  not corrupted  not corrupted  ...  not corrupted  not corrupted   
9998  not corrupted  not corrupted  ...  not corrupted  not corrupted   
9999  not corrupted  not corrupted  ...  not corrupted  not corrupted   

                 42             43             44             45  \
0     not corrupted  not corrupted  not corrupted  not corrupted   
1     not corrupted  not corrupted  not corrupted  not corrupted   
2     not corrupted  not corrupted  not corrupted  not corrupted   
3     not corrupted  not corrupted  not corrupted  not corrupted   
4     not corrupted  not corrupted  not corrupted  not corrupted   
...             ...            ...            ...            ...   
9995  not corrupted  not corrupted  not corrupted  not corrupted   
9996  not corrupted  not corrupted  not corrupted  not corrupted   
9997  not corrupted  not corrupted  not corrupted  not corrupted   
9998  not corrupted  not corrupted  not corrupted  not corrupted   
9999  not corrupted  not corrupted  not corrupted  not corrupted   

                 46             47             48             49  
0     not corrupted  not corrupted  not corrupted  not corrupted  
1     not corrupted  not corrupted  not corrupted  not corrupted  
2     not corrupted  not corrupted  not corrupted  not corrupted  
3     not corrupted  not corrupted  not corrupted  not corrupted  
4     not corrupted  not corrupted  not corrupted  not corrupted  
...             ...            ...            ...            ...  
9995  not corrupted  not corrupted  not corrupted  not corrupted  
9996  not corrupted  not corrupted  not corrupted  not corrupted  
9997  not corrupted  not corrupted  not corrupted  not corrupted  
9998  not corrupted

- Step 3: Write a function that tells if all trials were not corrupted, then apply to dataframe.

In [66]:
def no_intallation_issues(one_row: pd.Series) -> bool:
    return (one_row == 'not corrupted').all()

In [67]:
installdf.apply(no_intallation_issues, axis = 1)

0        True
1        True
2        True
3        True
4        True
        ...  
9995     True
9996     True
9997     True
9998    False
9999     True
Length: 10000, dtype: bool

- Step 4: To answer the question "What are the odds?" use .mean()

In [70]:
odds_of_successful_installation_for_50_students = installdf.apply(no_intallation_issues, axis = 1).mean()

In [71]:
odds_of_successful_installation_for_50_students

0.8167

### for 100 students?

In [73]:
install1 = np.random.choice(['corrupted','not corrupted'], size = (10_000 , 100), p=[.004, .996])
install1

array([['not corrupted', 'not corrupted', 'not corrupted', ...,
        'not corrupted', 'not corrupted', 'not corrupted'],
       ['not corrupted', 'not corrupted', 'not corrupted', ...,
        'not corrupted', 'not corrupted', 'not corrupted'],
       ['not corrupted', 'not corrupted', 'not corrupted', ...,
        'not corrupted', 'not corrupted', 'not corrupted'],
       ...,
       ['not corrupted', 'not corrupted', 'not corrupted', ...,
        'not corrupted', 'not corrupted', 'not corrupted'],
       ['not corrupted', 'not corrupted', 'not corrupted', ...,
        'not corrupted', 'not corrupted', 'not corrupted'],
       ['not corrupted', 'not corrupted', 'not corrupted', ...,
        'not corrupted', 'not corrupted', 'not corrupted']], dtype='<U13')

In [74]:
install1df = pd.DataFrame(install)
install1df

0              1              2              3   \
0     not corrupted  not corrupted  not corrupted  not corrupted   
1     not corrupted  not corrupted  not corrupted  not corrupted   
2     not corrupted  not corrupted  not corrupted  not corrupted   
3     not corrupted  not corrupted  not corrupted  not corrupted   
4     not corrupted  not corrupted  not corrupted  not corrupted   
...             ...            ...            ...            ...   
9995  not corrupted  not corrupted  not corrupted  not corrupted   
9996  not corrupted  not corrupted  not corrupted  not corrupted   
9997  not corrupted  not corrupted  not corrupted  not corrupted   
9998  not corrupted  not corrupted  not corrupted  not corrupted   
9999  not corrupted  not corrupted  not corrupted  not corrupted   

                 4              5              6              7   \
0     not corrupted  not corrupted  not corrupted  not corrupted   
1     not corrupted  not corrupted  not corrupted  not corrupted   
2     not corrupted  not corrupted  not corrupted  not corrupted   
3     not corrupted  not corrupted  not corrupted  not corrupted   
4     not corrupted  not corrupted  not corrupted  not corrupted   
...             ...            ...            ...            ...   
9995  not corrupted  not corrupted  not corrupted  not corrupted   
9996  not corrupted  not corrupted  not corrupted  not corrupted   
9997  not corrupted  not corrupted  not corrupted  not corrupted   
9998  not corrupted  not corrupted  not corrupted  not corrupted   
9999  not corrupted  not corrupted  not corrupted  not corrupted   

                 8              9   ...             40             41  \
0     not corrupted  not corrupted  ...  not corrupted  not corrupted   
1     not corrupted  not corrupted  ...  not corrupted  not corrupted   
2     not corrupted  not corrupted  ...  not corrupted  not corrupted   
3     not corrupted  not corrupted  ...  not corrupted  not corrupted   
4     not corrupted  not corrupted  ...  not corrupted  not corrupted   
...             ...            ...  ...            ...            ...   
9995  not corrupted  not corrupted  ...  not corrupted  not corrupted   
9996  not corrupted  not corrupted  ...  not corrupted  not corrupted   
9997  not corrupted  not corrupted  ...  not corrupted  not corrupted   
9998  not corrupted  not corrupted  ...  not corrupted  not corrupted   
9999  not corrupted  not corrupted  ...  not corrupted  not corrupted   

                 42             43             44             45  \
0     not corrupted  not corrupted  not corrupted  not corrupted   
1     not corrupted  not corrupted  not corrupted  not corrupted   
2     not corrupted  not corrupted  not corrupted  not corrupted   
3     not corrupted  not corrupted  not corrupted  not corrupted   
4     not corrupted  not corrupted  not corrupted  not corrupted   
...             ...            ...            ...            ...   
9995  not corrupted  not corrupted  not corrupted  not corrupted   
9996  not corrupted  not corrupted  not corrupted  not corrupted   
9997  not corrupted  not corrupted  not corrupted  not corrupted   
9998  not corrupted  not corrupted  not corrupted  not corrupted   
9999  not corrupted  not corrupted  not corrupted  not corrupted   

                 46             47             48             49  
0     not corrupted  not corrupted  not corrupted  not corrupted  
1     not corrupted  not corrupted  not corrupted  not corrupted  
2     not corrupted  not corrupted  not corrupted  not corrupted  
3     not corrupted  not corrupted  not corrupted  not corrupted  
4     not corrupted  not corrupted  not corrupted  not corrupted  
...             ...            ...            ...            ...  
9995  not corrupted  not corrupted  not corrupted  not corrupted  
9996  not corrupted  not corrupted  not corrupted  not corrupted  
9997  not corrupted  not corrupted  not corrupted  not corrupted  
9998  not corrupted

In [75]:
odds_of_successful_installation_for_100_students = install1df.apply(no_intallation_issues, axis = 1).mean()

In [76]:
odds_of_successful_installation_for_100_students 

0.8167