In [1]:
%matplotlib inline
import numpy as np
import pandas as pd
flips = np.random.choice(['Heads', 'Tails'], size =5)


In [2]:
flips == 'Heads'

array([False, False, False,  True,  True])

In [3]:
(flips == 'Heads').mean()

0.4

In [4]:
#### as we increase the numer of trials, our acutal probability approaches the theoretical probability

In [5]:
flips = np.random.choice(['Heads', 'Tails'], size =100000)

In [6]:
(flips == 'Heads').mean()

0.50124

### 1. How likely is it that you roll doubles when rolling two dice?

1. Represent your data
2. Make a matrix
3. Aggregate row-wise

In [7]:
roll_results = np.random.choice([1,2,3,4,5,6], size=(10_000 ,2))
roll_results

array([[6, 6],
       [2, 3],
       [1, 3],
       ...,
       [6, 6],
       [5, 2],
       [5, 2]])

- Because the row-wise aggregate is more complicated than an simple sum, turn the np array into a pandas dataframe

In [8]:
df = pd.DataFrame(roll_results)
df

0  1
0     6  6
1     2  3
2     1  3
3     6  4
4     5  1
...  .. ..
9995  2  4
9996  1  3
9997  6  6
9998  5  2
9999  5  2

[10000 rows x 2 columns]

- Now write a function that checks to see if each observation is a double (same number on each roll)
- Then apply that to the whole dataframe one row at a time

In [9]:
def are_doubles(one_observation: pd.Series) -> bool:
    return (one_observation == 1).all() or (one_observation == 2).all() or (one_observation == 3).all() or (one_observation == 4).all() or (one_observation == 5).all() or (one_observation == 6).all()

In [10]:
df.apply(are_doubles , axis = 1)

0        True
1       False
2       False
3       False
4       False
        ...  
9995    False
9996    False
9997     True
9998    False
9999    False
Length: 10000, dtype: bool

- To answer the question "How likely?" use the .mean() function to get a percent. This represents the probablitily that any of these rolls are doubles of any kind

In [11]:
df.apply(are_doubles , axis = 1).mean()

0.1721

### 2. If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

- Represent your data
- Make a matrix
- Aggregate row-wise
- Aggregate of aggregate

- Step 1: Use an np array and random choice to represent the results of flipping 8 coins 10,000 times

In [12]:
flip_results = np.random.choice(["Heads","Tails"], size = (10_000, 8))
flip_results

array([['Heads', 'Heads', 'Heads', ..., 'Heads', 'Heads', 'Tails'],
       ['Heads', 'Heads', 'Tails', ..., 'Tails', 'Heads', 'Heads'],
       ['Heads', 'Tails', 'Tails', ..., 'Tails', 'Tails', 'Heads'],
       ...,
       ['Heads', 'Heads', 'Tails', ..., 'Heads', 'Tails', 'Tails'],
       ['Tails', 'Tails', 'Heads', ..., 'Heads', 'Tails', 'Tails'],
       ['Heads', 'Tails', 'Tails', ..., 'Tails', 'Tails', 'Heads']],
      dtype='<U5')

- Step 2: Turn results into boolean values where 'Heads' is True and 'Tails' is False

In [13]:
is_heads = (flip_results == 'Heads')
is_heads

array([[ True,  True,  True, ...,  True,  True, False],
       [ True,  True, False, ..., False,  True,  True],
       [ True, False, False, ..., False, False,  True],
       ...,
       [ True,  True, False, ...,  True, False, False],
       [False, False,  True, ...,  True, False, False],
       [ True, False, False, ..., False, False,  True]])

- Step 3: Sum all the rows

In [14]:
number_of_heads_in_each_observation = is_heads.sum(axis=1)
number_of_heads_in_each_observation

array([5, 4, 3, ..., 3, 3, 2])

- Step 4: Count all the instances that the total equals 3. This represents only 3 heads in each observation or row

In [15]:
only_3_heads = (number_of_heads_in_each_observation == 3)
only_3_heads

array([False, False,  True, ...,  True,  True, False])

- Step 4: To answer the question "What is the probablitily?" use the .mean() function.

In [16]:
only_3_heads.mean()

0.2172

### 3. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

- Represent your data
- Make a matrix
- Aggregate row-wise
- Aggregate of aggregate

- Step 1: Represent the data in an np array. The number of trials is two as this represents the two bilboards the person will drive past. There is a higher probability that the student chosen will be from the web development class, so include a probability aregument that represents this

- There are 4 elements. Three of which are the same, one is different

In [17]:
cohorts = np.random.choice(["WD","DS"], size = (10_000, 2), p=[.75,.25])
cohorts

array([['DS', 'WD'],
       ['WD', 'WD'],
       ['WD', 'DS'],
       ...,
       ['WD', 'WD'],
       ['WD', 'DS'],
       ['WD', 'WD']], dtype='<U2')

- Step 2: Because the row-wise aggregate is more complicated than an simple sum, turn the np array into a pandas dataframe

In [18]:
cohortsdf = pd.DataFrame(cohorts)
cohortsdf

0   1
0     DS  WD
1     WD  WD
2     WD  DS
3     WD  WD
4     WD  WD
...   ..  ..
9995  WD  DS
9996  WD  WD
9997  WD  WD
9998  WD  DS
9999  WD  WD

[10000 rows x 2 columns]

- Step 3: Determine how many times both bilboards have a data science student by writing a function, then apply that function to the entire dataframe

In [19]:
def are_both_data_science(one_row: pd.Series) -> bool:
    return (one_row == 'DS').all()

In [20]:
cohortsdf.apply(are_both_data_science, axis = 1)

0       False
1       False
2       False
3       False
4       False
        ...  
9995    False
9996    False
9997    False
9998    False
9999    False
Length: 10000, dtype: bool

- Step 4: Now you have a dataframe that is showing whether or not each observation or row has both data science students. To answer the question "What are the odds?" use .mean()

In [21]:
what_are_the_odds = cohortsdf.apply(are_both_data_science, axis = 1).mean()

In [22]:
what_are_the_odds

0.0614

### 4. Codeup students buy, on average, 3 poptart packages (+- 1.5) a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon?

- Represent your data
- Make a matrix
- Aggregate row-wise
- Aggregate of aggregate

- Step 1: Represent the data that shows average of 3 poptart purchases with standard deviation of 1.5. Use np.random.normal

In [23]:
poptart_purchases = np.random.normal(3,1.5, size = (10_000, 5))
rounded_poptart_purchases = poptart_purchases.round()
rounded_poptart_purchases

array([[-1.,  3.,  2.,  3.,  5.],
       [ 4.,  5.,  4.,  6.,  4.],
       [ 4.,  3.,  0.,  1.,  3.],
       ...,
       [ 4.,  4.,  5.,  6.,  2.],
       [ 5., -1.,  1.,  0.,  2.],
       [ 6.,  4.,  4.,  4.,  5.]])

- Step 2: There must be at least 1 poptart left at the end of the day on Friday in order to make a purchase. Sum the days of the week and compare it to 16

In [24]:
rounded_poptart_purchases_sum = rounded_poptart_purchases.sum(axis=1)
rounded_poptart_purchases_sum

array([12., 23., 11., ..., 21.,  7., 23.])

In [25]:
at_least_one_poptart_left_on_Friday = (rounded_poptart_purchases_sum <= 16)
at_least_one_poptart_left_on_Friday

array([ True, False,  True, ..., False,  True, False])

- Step: 3 To answer the question "How likely?" use .mean()

In [26]:
at_least_one_poptart_left_on_Friday.mean()

0.6734

### 5. Compare Heights
### Men have an average height of 178 cm and standard deviation of 8cm.
### Women have a mean of 170, sd = 6cm.
### If a man and woman are chosen at random, P(woman taller than man)?

- Represent your data
- Make a matrix
- Aggregate row-wise
- Aggregate of aggregate

- Step 1: Represent data in np array with np.random.normal

In [27]:
men_height = np.random.normal(178, 8, size = 10_000)
men_height

array([165.44908298, 180.69387943, 171.48967767, ..., 180.23294887,
       188.07726492, 174.4139833 ])

In [28]:
women_height = np.random.normal(170, 6, size = 10_000)
women_height

array([178.42150706, 174.35538045, 156.12916908, ..., 169.13740074,
       182.44097789, 166.71775945])

- Step 2: Create dataframe with men and women heights

In [29]:
height = pd.DataFrame({'Average Mens Height': men_height, 'Average Womens Height': women_height})

In [30]:
height

Average Mens Height  Average Womens Height
0              165.449083             178.421507
1              180.693879             174.355380
2              171.489678             156.129169
3              167.433377             163.603631
4              197.902595             176.675891
...                   ...                    ...
9995           183.175999             171.583828
9996           154.781519             174.941653
9997           180.232949             169.137401
9998           188.077265             182.440978
9999           174.413983             166.717759

[10000 rows x 2 columns]

- Step 3: Compare if average height of women is more than average height of man. This will create a boolean value of the instances where this is True or False

In [31]:
height['Woman is taller than Man'] = (height['Average Womens Height'] > height['Average Mens Height'])

In [32]:
height

Average Mens Height  Average Womens Height  Woman is taller than Man
0              165.449083             178.421507                      True
1              180.693879             174.355380                     False
2              171.489678             156.129169                     False
3              167.433377             163.603631                     False
4              197.902595             176.675891                     False
...                   ...                    ...                       ...
9995           183.175999             171.583828                     False
9996           154.781519             174.941653                      True
9997           180.232949             169.137401                     False
9998           188.077265             182.440978                     False
9999           174.413983             166.717759                     False

[10000 rows x 3 columns]

In [33]:
probability_woman_is_taller_than_man= height['Woman is taller than Man'].mean()
probability_woman_is_taller_than_man

0.2083

### 6.  When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?
### What is the probability that we observe an installation issue within the first 150 students that download anaconda?

- Represent your data
- Make a matrix
- Aggregate row-wise
- Aggregate of aggregate

- Step 1: Represent data in np array with np.random.choice

In [34]:
install = np.random.choice(['corrupted','not corrupted'], size = (10_000 , 50), p=[.004, .996])
install

array([['not corrupted', 'not corrupted', 'not corrupted', ...,
        'not corrupted', 'not corrupted', 'not corrupted'],
       ['not corrupted', 'not corrupted', 'not corrupted', ...,
        'not corrupted', 'not corrupted', 'corrupted'],
       ['not corrupted', 'not corrupted', 'not corrupted', ...,
        'not corrupted', 'not corrupted', 'not corrupted'],
       ...,
       ['not corrupted', 'not corrupted', 'not corrupted', ...,
        'not corrupted', 'not corrupted', 'not corrupted'],
       ['not corrupted', 'not corrupted', 'not corrupted', ...,
        'not corrupted', 'not corrupted', 'not corrupted'],
       ['not corrupted', 'not corrupted', 'not corrupted', ...,
        'not corrupted', 'not corrupted', 'not corrupted']], dtype='<U13')

- Step 2: Because the row-wise aggregate is more complicated than an simple sum, turn the np array into a pandas dataframe

In [35]:
installdf = pd.DataFrame(install)
installdf

0              1              2              3   \
0     not corrupted  not corrupted  not corrupted  not corrupted   
1     not corrupted  not corrupted  not corrupted  not corrupted   
2     not corrupted  not corrupted  not corrupted  not corrupted   
3     not corrupted  not corrupted  not corrupted  not corrupted   
4     not corrupted  not corrupted  not corrupted  not corrupted   
...             ...            ...            ...            ...   
9995  not corrupted  not corrupted  not corrupted  not corrupted   
9996  not corrupted  not corrupted  not corrupted  not corrupted   
9997  not corrupted  not corrupted  not corrupted  not corrupted   
9998  not corrupted  not corrupted  not corrupted  not corrupted   
9999  not corrupted  not corrupted  not corrupted  not corrupted   

                 4              5              6              7   \
0     not corrupted  not corrupted  not corrupted  not corrupted   
1     not corrupted  not corrupted  not corrupted  not corrupted   
2     not corrupted  not corrupted  not corrupted  not corrupted   
3     not corrupted  not corrupted      corrupted  not corrupted   
4     not corrupted  not corrupted  not corrupted  not corrupted   
...             ...            ...            ...            ...   
9995  not corrupted  not corrupted  not corrupted  not corrupted   
9996  not corrupted  not corrupted  not corrupted  not corrupted   
9997  not corrupted  not corrupted  not corrupted  not corrupted   
9998  not corrupted  not corrupted  not corrupted  not corrupted   
9999  not corrupted  not corrupted  not corrupted  not corrupted   

                 8              9   ...             40             41  \
0     not corrupted  not corrupted  ...  not corrupted  not corrupted   
1     not corrupted  not corrupted  ...  not corrupted  not corrupted   
2     not corrupted  not corrupted  ...  not corrupted  not corrupted   
3     not corrupted  not corrupted  ...  not corrupted  not corrupted   
4     not corrupted  not corrupted  ...  not corrupted  not corrupted   
...             ...            ...  ...            ...            ...   
9995  not corrupted  not corrupted  ...  not corrupted  not corrupted   
9996  not corrupted  not corrupted  ...  not corrupted  not corrupted   
9997  not corrupted  not corrupted  ...  not corrupted  not corrupted   
9998  not corrupted  not corrupted  ...  not corrupted  not corrupted   
9999  not corrupted  not corrupted  ...  not corrupted  not corrupted   

                 42             43             44             45  \
0     not corrupted  not corrupted  not corrupted  not corrupted   
1     not corrupted  not corrupted  not corrupted  not corrupted   
2     not corrupted  not corrupted  not corrupted  not corrupted   
3     not corrupted  not corrupted  not corrupted  not corrupted   
4     not corrupted  not corrupted  not corrupted  not corrupted   
...             ...            ...            ...            ...   
9995  not corrupted  not corrupted  not corrupted  not corrupted   
9996  not corrupted  not corrupted  not corrupted  not corrupted   
9997  not corrupted  not corrupted  not corrupted  not corrupted   
9998  not corrupted  not corrupted  not corrupted  not corrupted   
9999  not corrupted  not corrupted  not corrupted  not corrupted   

                 46             47             48             49  
0     not corrupted  not corrupted  not corrupted  not corrupted  
1     not corrupted  not corrupted  not corrupted      corrupted  
2     not corrupted  not corrupted  not corrupted  not corrupted  
3     not corrupted  not corrupted  not corrupted  not corrupted  
4     not corrupted  not corrupted  not corrupted  not corrupted  
...             ...            ...            ...            ...  
9995  not corrupted  not corrupted  not corrupted  not corrupted  
9996  not corrupted  not corrupted  not corrupted  not corrupted  
9997  not corrupted  not corrupted  not corrupted  not corrupted  
9998  not corrupted

- Step 3: Write a function that tells if all trials were not corrupted, then apply to dataframe.

In [36]:
def no_intallation_issues(one_row: pd.Series) -> bool:
    return (one_row == 'not corrupted').all()

In [37]:
installdf.apply(no_intallation_issues, axis = 1)

0        True
1       False
2        True
3       False
4        True
        ...  
9995     True
9996     True
9997     True
9998     True
9999     True
Length: 10000, dtype: bool

- Step 4: To answer the question "What are the odds?" use .mean()

In [38]:
odds_of_successful_installation_for_50_students = installdf.apply(no_intallation_issues, axis = 1).mean()

In [39]:
odds_of_successful_installation_for_50_students

0.8179

### for 100 students?

In [40]:
install1 = np.random.choice(['corrupted','not corrupted'], size = (10_000 , 100), p=[.004, .996])
install1

array([['not corrupted', 'not corrupted', 'not corrupted', ...,
        'not corrupted', 'not corrupted', 'not corrupted'],
       ['not corrupted', 'not corrupted', 'not corrupted', ...,
        'not corrupted', 'not corrupted', 'not corrupted'],
       ['not corrupted', 'not corrupted', 'not corrupted', ...,
        'not corrupted', 'not corrupted', 'not corrupted'],
       ...,
       ['not corrupted', 'not corrupted', 'not corrupted', ...,
        'not corrupted', 'not corrupted', 'not corrupted'],
       ['not corrupted', 'not corrupted', 'not corrupted', ...,
        'not corrupted', 'not corrupted', 'not corrupted'],
       ['not corrupted', 'not corrupted', 'not corrupted', ...,
        'not corrupted', 'not corrupted', 'not corrupted']], dtype='<U13')

In [41]:
install1df = pd.DataFrame(install)
install1df

0              1              2              3   \
0     not corrupted  not corrupted  not corrupted  not corrupted   
1     not corrupted  not corrupted  not corrupted  not corrupted   
2     not corrupted  not corrupted  not corrupted  not corrupted   
3     not corrupted  not corrupted  not corrupted  not corrupted   
4     not corrupted  not corrupted  not corrupted  not corrupted   
...             ...            ...            ...            ...   
9995  not corrupted  not corrupted  not corrupted  not corrupted   
9996  not corrupted  not corrupted  not corrupted  not corrupted   
9997  not corrupted  not corrupted  not corrupted  not corrupted   
9998  not corrupted  not corrupted  not corrupted  not corrupted   
9999  not corrupted  not corrupted  not corrupted  not corrupted   

                 4              5              6              7   \
0     not corrupted  not corrupted  not corrupted  not corrupted   
1     not corrupted  not corrupted  not corrupted  not corrupted   
2     not corrupted  not corrupted  not corrupted  not corrupted   
3     not corrupted  not corrupted      corrupted  not corrupted   
4     not corrupted  not corrupted  not corrupted  not corrupted   
...             ...            ...            ...            ...   
9995  not corrupted  not corrupted  not corrupted  not corrupted   
9996  not corrupted  not corrupted  not corrupted  not corrupted   
9997  not corrupted  not corrupted  not corrupted  not corrupted   
9998  not corrupted  not corrupted  not corrupted  not corrupted   
9999  not corrupted  not corrupted  not corrupted  not corrupted   

                 8              9   ...             40             41  \
0     not corrupted  not corrupted  ...  not corrupted  not corrupted   
1     not corrupted  not corrupted  ...  not corrupted  not corrupted   
2     not corrupted  not corrupted  ...  not corrupted  not corrupted   
3     not corrupted  not corrupted  ...  not corrupted  not corrupted   
4     not corrupted  not corrupted  ...  not corrupted  not corrupted   
...             ...            ...  ...            ...            ...   
9995  not corrupted  not corrupted  ...  not corrupted  not corrupted   
9996  not corrupted  not corrupted  ...  not corrupted  not corrupted   
9997  not corrupted  not corrupted  ...  not corrupted  not corrupted   
9998  not corrupted  not corrupted  ...  not corrupted  not corrupted   
9999  not corrupted  not corrupted  ...  not corrupted  not corrupted   

                 42             43             44             45  \
0     not corrupted  not corrupted  not corrupted  not corrupted   
1     not corrupted  not corrupted  not corrupted  not corrupted   
2     not corrupted  not corrupted  not corrupted  not corrupted   
3     not corrupted  not corrupted  not corrupted  not corrupted   
4     not corrupted  not corrupted  not corrupted  not corrupted   
...             ...            ...            ...            ...   
9995  not corrupted  not corrupted  not corrupted  not corrupted   
9996  not corrupted  not corrupted  not corrupted  not corrupted   
9997  not corrupted  not corrupted  not corrupted  not corrupted   
9998  not corrupted  not corrupted  not corrupted  not corrupted   
9999  not corrupted  not corrupted  not corrupted  not corrupted   

                 46             47             48             49  
0     not corrupted  not corrupted  not corrupted  not corrupted  
1     not corrupted  not corrupted  not corrupted      corrupted  
2     not corrupted  not corrupted  not corrupted  not corrupted  
3     not corrupted  not corrupted  not corrupted  not corrupted  
4     not corrupted  not corrupted  not corrupted  not corrupted  
...             ...            ...            ...            ...  
9995  not corrupted  not corrupted  not corrupted  not corrupted  
9996  not corrupted  not corrupted  not corrupted  not corrupted  
9997  not corrupted  not corrupted  not corrupted  not corrupted  
9998  not corrupted

In [42]:
odds_of_successful_installation_for_100_students = install1df.apply(no_intallation_issues, axis = 1).mean()

In [43]:
odds_of_successful_installation_for_100_students 

0.8179

### 7. There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?

- Represent your data
- Make a matrix
- Aggregate row-wise
- Aggregate of aggregate

- Step 1: Represent data in np array with np.random.choice

In [44]:
food_truck = np.random.choice(['FT','NFT'], size = (10_000, 3), p = [.70,.30])
food_truck

array([['FT', 'FT', 'NFT'],
       ['NFT', 'NFT', 'FT'],
       ['FT', 'NFT', 'FT'],
       ...,
       ['NFT', 'FT', 'NFT'],
       ['FT', 'FT', 'FT'],
       ['FT', 'NFT', 'NFT']], dtype='<U3')

- Step 2: Convert np array to pd datafram due to complex row-wise aggregation

In [45]:
foodtruckdf = pd.DataFrame(food_truck)
foodtruckdf

0    1    2
0      FT   FT  NFT
1     NFT  NFT   FT
2      FT  NFT   FT
3     NFT  NFT   FT
4      FT  NFT   FT
...   ...  ...  ...
9995   FT  NFT  NFT
9996   FT  NFT   FT
9997  NFT   FT  NFT
9998   FT   FT   FT
9999   FT  NFT  NFT

[10000 rows x 3 columns]

- Step 3: Write a function that tells if the food truck has not been seen in the last 3 days

In [46]:
def has_not_been_seen_in_last_3_days(sighting: pd.Series) -> bool:
    return (sighting == 'NFT').all() and (sighting == 'NFT').all() and (sighting == 'NFT').all()

- Step 3: The food truck has not been seen in three days. Create a boolean column which show true or false if the first three days show 'No Food Truck"

In [47]:
foodtruckdf['Not in last 3 days'] = foodtruckdf.apply(has_not_been_seen_in_last_3_days, axis = 1)
foodtruckdf

0    1    2  Not in last 3 days
0      FT   FT  NFT               False
1     NFT  NFT   FT               False
2      FT  NFT   FT               False
3     NFT  NFT   FT               False
4      FT  NFT   FT               False
...   ...  ...  ...                 ...
9995   FT  NFT  NFT               False
9996   FT  NFT   FT               False
9997  NFT   FT  NFT               False
9998   FT   FT   FT               False
9999   FT  NFT  NFT               False

[10000 rows x 4 columns]

- Step 4: To answer the question "How unlikely?" use .mean()

In [48]:
how_unlikely = foodtruckdf['Not in last 3 days'].mean()

In [49]:
how_unlikely

0.0276

### 8. If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?

- Represent your data
- Make a matrix
- Aggregate row-wise
- Aggregate of aggregate

- Step 1: Represent data in np array with np.random.choice

In [103]:
birthdays = np.random.randint(1,366, (10000, 23))

In [104]:
birthdaysdf = pd.DataFrame(birthdays)

In [108]:
(birthdaysdf.nunique(axis=1) <23).mean()

0.5112